import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import Link from "next/link";
import Providers from "./providers";
import Image from "next/image"
import { getServerSession } from 'next-auth/next'
import { options } from "../api/auth/[...nextauth]/options";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  const session = await getServerSession(options)

  return (
    <html lang="en" >
      <Providers>
        <body
          data-theme="dark"
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <div className="navbar bg-base-100">
            <div className="flex-1">
              <a className="btn btn-ghost text-xl">
                <Image
                  src="https://dex-bin.bnbstatic.com/static/dapp-uploads/1lalKyaw4nxafPLQMCRzC"
                  alt="cybertitans"
                  width={50}
                  height={50}
                />
                Cybertitans
              </a>
            </div>
            <div className="flex-none">
              <ul className="menu menu-horizontal px-1">
                {!session &&  <li><Link href={"/google/signin"}>Sign in</Link></li>}
                
                {session && 
                // @ts-ignore
                <li><Link href={"/"}>{session.user.name}</Link></li>}
                {/* <li>
                  <details>
                    <summary>Parent</summary>
                    <ul className="bg-base-100 rounded-t-none p-2">
                      <li><a>Link 1</a></li>
                      <li><a>Link 2</a></li>
                    </ul>
                  </details>
                </li> */}
              </ul>
            </div>
          </div>
          {children}
        </body>
      </Providers>
    </html>
  );
}
